# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /media/pavel/Files/apps/programming/clion-2017.2.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /media/pavel/Files/apps/programming/clion-2017.2.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pavel/CLionProjects/chess_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pavel/CLionProjects/chess_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/media/pavel/Files/apps/programming/clion-2017.2.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/media/pavel/Files/apps/programming/clion-2017.2.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavel/CLionProjects/chess_engine/CMakeFiles /home/pavel/CLionProjects/chess_engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pavel/CLionProjects/chess_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess_engine

# Build rule for target.
chess_engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess_engine
.PHONY : chess_engine

# fast build rule for target.
chess_engine/fast:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/build
.PHONY : chess_engine/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/main.cpp.s
.PHONY : main.cpp.s

src/Bishop_move.o: src/Bishop_move.cpp.o

.PHONY : src/Bishop_move.o

# target to build an object file
src/Bishop_move.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Bishop_move.cpp.o
.PHONY : src/Bishop_move.cpp.o

src/Bishop_move.i: src/Bishop_move.cpp.i

.PHONY : src/Bishop_move.i

# target to preprocess a source file
src/Bishop_move.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Bishop_move.cpp.i
.PHONY : src/Bishop_move.cpp.i

src/Bishop_move.s: src/Bishop_move.cpp.s

.PHONY : src/Bishop_move.s

# target to generate assembly for a file
src/Bishop_move.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Bishop_move.cpp.s
.PHONY : src/Bishop_move.cpp.s

src/Board.o: src/Board.cpp.o

.PHONY : src/Board.o

# target to build an object file
src/Board.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Board.cpp.o
.PHONY : src/Board.cpp.o

src/Board.i: src/Board.cpp.i

.PHONY : src/Board.i

# target to preprocess a source file
src/Board.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Board.cpp.i
.PHONY : src/Board.cpp.i

src/Board.s: src/Board.cpp.s

.PHONY : src/Board.s

# target to generate assembly for a file
src/Board.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Board.cpp.s
.PHONY : src/Board.cpp.s

src/Knight_move.o: src/Knight_move.cpp.o

.PHONY : src/Knight_move.o

# target to build an object file
src/Knight_move.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Knight_move.cpp.o
.PHONY : src/Knight_move.cpp.o

src/Knight_move.i: src/Knight_move.cpp.i

.PHONY : src/Knight_move.i

# target to preprocess a source file
src/Knight_move.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Knight_move.cpp.i
.PHONY : src/Knight_move.cpp.i

src/Knight_move.s: src/Knight_move.cpp.s

.PHONY : src/Knight_move.s

# target to generate assembly for a file
src/Knight_move.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Knight_move.cpp.s
.PHONY : src/Knight_move.cpp.s

src/Move.o: src/Move.cpp.o

.PHONY : src/Move.o

# target to build an object file
src/Move.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Move.cpp.o
.PHONY : src/Move.cpp.o

src/Move.i: src/Move.cpp.i

.PHONY : src/Move.i

# target to preprocess a source file
src/Move.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Move.cpp.i
.PHONY : src/Move.cpp.i

src/Move.s: src/Move.cpp.s

.PHONY : src/Move.s

# target to generate assembly for a file
src/Move.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Move.cpp.s
.PHONY : src/Move.cpp.s

src/Pawn_move.o: src/Pawn_move.cpp.o

.PHONY : src/Pawn_move.o

# target to build an object file
src/Pawn_move.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Pawn_move.cpp.o
.PHONY : src/Pawn_move.cpp.o

src/Pawn_move.i: src/Pawn_move.cpp.i

.PHONY : src/Pawn_move.i

# target to preprocess a source file
src/Pawn_move.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Pawn_move.cpp.i
.PHONY : src/Pawn_move.cpp.i

src/Pawn_move.s: src/Pawn_move.cpp.s

.PHONY : src/Pawn_move.s

# target to generate assembly for a file
src/Pawn_move.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Pawn_move.cpp.s
.PHONY : src/Pawn_move.cpp.s

src/Rook_move.o: src/Rook_move.cpp.o

.PHONY : src/Rook_move.o

# target to build an object file
src/Rook_move.cpp.o:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Rook_move.cpp.o
.PHONY : src/Rook_move.cpp.o

src/Rook_move.i: src/Rook_move.cpp.i

.PHONY : src/Rook_move.i

# target to preprocess a source file
src/Rook_move.cpp.i:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Rook_move.cpp.i
.PHONY : src/Rook_move.cpp.i

src/Rook_move.s: src/Rook_move.cpp.s

.PHONY : src/Rook_move.s

# target to generate assembly for a file
src/Rook_move.cpp.s:
	$(MAKE) -f CMakeFiles/chess_engine.dir/build.make CMakeFiles/chess_engine.dir/src/Rook_move.cpp.s
.PHONY : src/Rook_move.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... chess_engine"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Bishop_move.o"
	@echo "... src/Bishop_move.i"
	@echo "... src/Bishop_move.s"
	@echo "... src/Board.o"
	@echo "... src/Board.i"
	@echo "... src/Board.s"
	@echo "... src/Knight_move.o"
	@echo "... src/Knight_move.i"
	@echo "... src/Knight_move.s"
	@echo "... src/Move.o"
	@echo "... src/Move.i"
	@echo "... src/Move.s"
	@echo "... src/Pawn_move.o"
	@echo "... src/Pawn_move.i"
	@echo "... src/Pawn_move.s"
	@echo "... src/Rook_move.o"
	@echo "... src/Rook_move.i"
	@echo "... src/Rook_move.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

